from typing import Dict, List, Any
from datetime import datetime

class ReportService:
    def generate_audit_report(
        self, 
        repo_url: str, 
        score_data: Dict[str, Any], 
        summary: str, 
        roadmap: List[str]
    ) -> str:
        """
        Generates a professionally formatted Markdown report suitable for PDF conversion.
        """
        score = score_data.get("total_score", 0)
        level = score_data.get("level", "Unknown")
        breakdown = score_data.get("breakdown", {})
        
        # 1. Header & Overview
        report = []
        report.append(f"# GitHub Repository Evaluation Report")
        report.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d')}")
        report.append(f"**Target Repository:** {repo_url}")
        report.append("\n---")

        # 2. Executive Summary & Score
        report.append(f"\n## 1. Executive Summary")
        report.append(f"**Final Audit Score:** {score}/100")
        report.append(f"**Classification:** {level}")
        
        # Health Flags check
        flags = score_data.get("flags", {})
        active_flags = [f["description"] for f in flags.values() if f.get("value") is True]
        
        if active_flags:
            report.append(f"\n**⚠️ Critical Health Alerts:**")
            for alert in active_flags:
                report.append(f"- {alert}")
                
        report.append(f"\n**Assessor's Note:**\n{summary}")
        
        # 3. Detailed Dimensional Analysis
        report.append(f"\n## 2. Dimensional Analysis")
        
        strengths = []
        improvements = []
        
        for category, details in breakdown.items():
            cat_score = details.get("score", 0)
            max_score = details.get("max_score", 20)
            reasons = details.get("reasons", [])
            
            # Categorize reasons
            for r in reasons:
                if r.startswith("✅"):
                    strengths.append(f"[{category}] {r[2:]}")
                elif r.startswith("❌") or r.startswith("⚠️"):
                    improvements.append(f"[{category}] {r}") # Keep emoji for bad ones or strip? Keeping for clarity
                    
            report.append(f"\n### {category}")
            report.append(f"**Score:** {cat_score}/{max_score}")
            report.append("**Audit Findings:**")
            for r in reasons:
                report.append(f"- {r}")

        # 4. Key Strengths
        report.append(f"\n## 3. Key Strengths")
        if strengths:
            for s in strengths:
                report.append(f"- {s}")
        else:
            report.append("- No significant structural strengths identified.")

        # 5. Areas for Improvement
        report.append(f"\n## 4. Operational Gaps & Risks")
        if improvements:
            for i in improvements:
                report.append(f"- {i}")
        else:
            report.append("- No critical deficiencies found.")

        # 6. Strategic Roadmap
        report.append(f"\n## 5. Remediation Roadmap")
        for step in roadmap:
            report.append(f"1. {step}")

        # 7. Disclaimer
        report.append("\n---")
        report.append("## Disclaimer")
        report.append("This report is generated by an automated AI auditing system. The evaluation is based on static analysis of repository metadata, file structure, and commit history. It does not execute code or perform dynamic testing. Scores are heuristic indicators of engineering maturity and should be used as a guideline for professional development.")
        
        return "\n".join(report)
